/**
 * Loads the pre-fetched Wikidata JSON packs in data/wikidata-imports/ and
 * pipes them through the cameragrail.bulk_upsert_cameras() Postgres
 * function. Faster and more reliable than re-running SPARQL — the packs
 * were generated by the agent and committed.
 *
 * Usage:
 *   SUPABASE_SERVICE_ROLE_KEY=... npx tsx scripts/load-wikidata-packs.ts
 *
 * Each pack is a JSON array of compact records:
 *   {s, b, bs, m, f, fs, ys, ye, c, mt, h, w}
 * (slug, brand, brand_slug, model, format, format_slug, year_start,
 *  year_end, country, mount, history, wikidata Q-id).
 */
import { readFileSync, readdirSync } from 'node:fs';
import { join } from 'node:path';
import { supabaseService } from '../src/lib/supabase/server';

const PACK_DIR = join(process.cwd(), 'data', 'wikidata-imports');

async function main() {
  const files = readdirSync(PACK_DIR)
    .filter((f) => f.endsWith('.json'))
    .sort();
  if (files.length === 0) {
    console.error(`No pack files in ${PACK_DIR}`);
    process.exit(1);
  }
  console.log(`Loading ${files.length} pack(s) into Supabase…`);

  const supabase = supabaseService();
  let total = 0;
  for (const file of files) {
    const raw = readFileSync(join(PACK_DIR, file), 'utf8');
    const rows = JSON.parse(raw) as unknown[];
    const { data, error } = await supabase.rpc('bulk_upsert_cameras', {
      payload: rows,
    });
    if (error) {
      console.error(`  ${file}: error`, error.message);
      continue;
    }
    const n = typeof data === 'number' ? data : 0;
    total += n;
    console.log(`  ${file}: upserted ${n} rows`);
  }
  console.log(`Done. Total upserted: ${total}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
