/**
 * Cornerstone-post seeder.
 *
 * Reads .html files from /content/blog and emits INSERT statements for the
 * cameragrail.blog_posts table. Pairs front-matter style metadata expressed
 * as HTML comments at the top of each file:
 *
 *   <!-- title: Why the Leica M3 still defines the rangefinder -->
 *   <!-- slug: leica-m3-why-it-still-defines-rangefinder -->
 *   <!-- category: Buying guide -->
 *   <!-- excerpt: One or two sentences. -->
 *   <!-- meta_title: ... -->
 *   <!-- meta_description: ... -->
 *   <!-- cover_image: https://... -->
 *   <!-- cover_image_alt: ... -->
 *   <!-- author_name: CameraGrail Editors -->
 *   <!-- tags: leica, rangefinder, buying guide -->
 *   <!-- read_time_minutes: 7 -->
 *   <!-- is_featured: true -->
 *
 * Anything before the first <h1>, <h2>, or <p> is treated as metadata.
 *
 * Usage:
 *   npx tsx scripts/seed-blog.ts > seed-blog.sql
 *   # then pipe seed-blog.sql to the Supabase MCP execute_sql tool, or
 *   # paste it into the SQL editor in the Supabase dashboard.
 */
import { readFileSync, readdirSync } from 'node:fs';
import { join, basename } from 'node:path';
import { SITE } from '../src/lib/site';

const CONTENT_DIR = join(process.cwd(), 'content/blog');

interface PostMeta {
  title: string;
  slug: string;
  category?: string;
  excerpt?: string;
  meta_title?: string;
  meta_description?: string;
  cover_image?: string;
  cover_image_alt?: string;
  author_name?: string;
  tags?: string[];
  read_time_minutes?: number;
  is_featured?: boolean;
  status?: 'draft' | 'published';
}

function parseMeta(raw: string, filename: string): { meta: PostMeta; body: string } {
  const meta: PostMeta = { title: '', slug: '' };
  const lines = raw.split('\n');
  let bodyStart = 0;
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    const m = line.match(/^<!--\s*([a-z_]+)\s*:\s*(.*?)\s*-->\s*$/i);
    if (!m) {
      if (line.trim() === '' || line.startsWith('<!--')) continue;
      bodyStart = i;
      break;
    }
    const [, key, value] = m;
    switch (key) {
      case 'title':
        meta.title = value;
        break;
      case 'slug':
        meta.slug = value;
        break;
      case 'category':
        meta.category = value;
        break;
      case 'excerpt':
        meta.excerpt = value;
        break;
      case 'meta_title':
        meta.meta_title = value;
        break;
      case 'meta_description':
        meta.meta_description = value;
        break;
      case 'cover_image':
        meta.cover_image = value;
        break;
      case 'cover_image_alt':
        meta.cover_image_alt = value;
        break;
      case 'author_name':
        meta.author_name = value;
        break;
      case 'tags':
        meta.tags = value
          .split(',')
          .map((t) => t.trim())
          .filter(Boolean);
        break;
      case 'read_time_minutes':
        meta.read_time_minutes = Number(value);
        break;
      case 'is_featured':
        meta.is_featured = value === 'true';
        break;
      case 'status':
        meta.status = value === 'draft' ? 'draft' : 'published';
        break;
    }
  }
  if (!meta.title) meta.title = basename(filename, '.html');
  if (!meta.slug) {
    meta.slug = meta.title
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/(^-|-$)/g, '');
  }
  const body = lines.slice(bodyStart).join('\n').trim();
  return { meta, body };
}

function esc(value: string | null | undefined): string {
  if (value == null) return 'NULL';
  return `'${value.replace(/'/g, "''")}'`;
}

function escArray(values: string[] | undefined): string {
  if (!values || values.length === 0) return 'NULL';
  const inner = values.map((v) => `"${v.replace(/"/g, '\\"')}"`).join(',');
  return `'{${inner}}'`;
}

function num(value: number | undefined | null): string {
  return value == null ? 'NULL' : String(value);
}

function bool(value: boolean | undefined): string {
  return value ? 'true' : 'false';
}

function main() {
  let files: string[];
  try {
    files = readdirSync(CONTENT_DIR).filter((f) => f.endsWith('.html'));
  } catch (err) {
    console.error(`No content/blog directory at ${CONTENT_DIR}.`);
    console.error('Create it and drop .html files in to seed posts.');
    process.exit(1);
  }
  if (files.length === 0) {
    console.error('No .html files found in content/blog.');
    process.exit(1);
  }

  console.log('-- Generated by scripts/seed-blog.ts');
  console.log('-- Pipe into the Supabase SQL editor or MCP execute_sql.');
  console.log('');

  for (const file of files.sort()) {
    const raw = readFileSync(join(CONTENT_DIR, file), 'utf8');
    const { meta, body } = parseMeta(raw, file);
    const status = meta.status ?? 'published';
    const publishedAt = status === 'published' ? 'now()' : 'NULL';

    console.log(`-- ${file}`);
    console.log(
      `INSERT INTO cameragrail.blog_posts (
  site, slug, title, category, excerpt, content, cover_image, cover_image_alt,
  meta_title, meta_description, seo_title, seo_description, author_name,
  read_time_minutes, tags, is_featured, status, is_published, published, published_at
) VALUES (
  ${esc(SITE.siteKey)},
  ${esc(meta.slug)},
  ${esc(meta.title)},
  ${esc(meta.category)},
  ${esc(meta.excerpt)},
  ${esc(body)},
  ${esc(meta.cover_image)},
  ${esc(meta.cover_image_alt)},
  ${esc(meta.meta_title)},
  ${esc(meta.meta_description)},
  ${esc(meta.meta_title)},
  ${esc(meta.meta_description)},
  ${esc(meta.author_name ?? SITE.founder)},
  ${num(meta.read_time_minutes)},
  ${escArray(meta.tags)},
  ${bool(meta.is_featured)},
  ${esc(status)},
  ${status === 'published' ? 'true' : 'false'},
  ${status === 'published' ? 'true' : 'false'},
  ${publishedAt}
)
ON CONFLICT (site, slug) DO UPDATE SET
  title = EXCLUDED.title,
  category = EXCLUDED.category,
  excerpt = EXCLUDED.excerpt,
  content = EXCLUDED.content,
  cover_image = EXCLUDED.cover_image,
  cover_image_alt = EXCLUDED.cover_image_alt,
  meta_title = EXCLUDED.meta_title,
  meta_description = EXCLUDED.meta_description,
  seo_title = EXCLUDED.seo_title,
  seo_description = EXCLUDED.seo_description,
  author_name = EXCLUDED.author_name,
  read_time_minutes = EXCLUDED.read_time_minutes,
  tags = EXCLUDED.tags,
  is_featured = EXCLUDED.is_featured,
  status = EXCLUDED.status,
  is_published = EXCLUDED.is_published,
  published = EXCLUDED.published,
  updated_at = now()
RETURNING slug;`,
    );
    console.log('');
  }
}

main();
